### ISSUE TITLE
media-manager response time up to 10 s 

### ISSUE THREAD

**Issue by shopmeister** [FriendsOfShopware/FroshBunnycdnMediaStorage#14]
Hey Hey, i am using the BunnyCDN adapter in a new shop, where i have around 8000 images. 
but when i try to access the media manager, it takes 5-15 s o connect to bunny and load the images there.
is there a way to short this time? i have often 500 Server timeout which that and it seems to be the connection
time to bunny that is slow. maybe you have an idea if there is something else i can make faster?
its the same issue when i try to upload images in a artikel. often i get 500 error or long loading times. 
maybe you have ideas what i maybe made wrong or configure better to avoid this.
greetz, matthias

**Comment by tinect** [comment]
Hey @epagogmbh,
sadly every request onto an image and thumbnail will first run a check, if the file exists.
While the storage isn't local, this behaviour of shopware is slowing down the system.
Therefore, I added a cache for these checks (located in `/var/cache/bunnycdn_storage`). After first check and request the status is cached in this folder, so it should be quiet faster.

Is there anything in your server logs relating to the errors? 

Log loading times when uploading: Yes, that's totally right. Because thumbnails are generated and transferred - all thumbnail sizes defined in album * 2 for high-res. This can exceed the time of uploading one image. Tipp: use https://github.com/FriendsOfShopware/FroshThumbnailProcessor

Greets, Sebastian
