### ISSUE TITLE
The selected file exceeds the configured maximum file size for uploads. Please select another file to upload.

### ISSUE THREAD

**Issue by JSNS9** [FriendsOfShopware/FroshBunnycdnMediaStorage#7]
Hi,

I have an issue when using the CDN.

I keep getting "The selected file exceeds the configured maximum file size for uploads. Please select another file to upload."

This only happens on the CDN plugin, When i revert to using the base system all uploads work correctly.

Is there any reason that this would happen?

**Comment by tinect** [comment]
Hi @JSNS9,
Related to message, there is no cap for filesize on side of plugin or bunnycdn.
But this message is sent on every error - not just in case the message says :-)

So there should occur another error. Would  you please double-check the credentials - https://github.com/FriendsOfShopware/FroshBunnycdnMediaStorage#usage

Otherwise, please check the error-log of shopware and/or server.

Best Regards,
Sebastian

**Comment by JSNS9** [comment]
Hi

There are no errors showing up either in shopware or server.

I cant even download images from the CDN. i am not sure what is going on with this. 

Thanks

**Comment by tinect** [comment]
Sounds just credential- and settings-related. Please check them.

**Comment by tinect** [comment]
Will be closed due to inactivity
